In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("flagged/FB_Scraped_5000.csv")
df = df.drop(["Unnamed: 0"], axis = 1)
df

,ACTORID,NAME,GROUPID,POSTID,TIME,CONTENT,COMMENTCOUNT,SHARECOUNT,LIKECOUNT,UPDATETIME
0,100018684546900,Carla Salomone Bondra,865107857005917,2129612443888779,2023-02-05 08:50:47,Any recommendations for something light and fu...,20,0,2,2023-02-05 15:59:12
1,1352593377,Ramona Hickey,865107857005917,2128962713953752,2023-02-04 13:38:40,Best romance books of all time.ðŸ©·ðŸ©·ðŸ©·,58,0,11,2023-02-05 15:59:12
2,1637440767,Tammy Johnson,865107857005917,2127957594054264,2023-02-03 06:08:51,Just bought this at the library store any thou...,57,0,53,2023-02-05 15:59:12
3,100033573947857,Sindhu Rathor,865107857005917,2123659931150697,2023-01-28 21:07:11,What are you reading this weekend?ðŸ“šWhat are yo...,725,3,80,2023-02-05 15:59:12
4,100000443850026,BeeDuangchai LoVan Kaew,865107857005917,2129380250578665,2023-02-05 01:04:19,Just got this today from mini hands shop Love...,6,0,8,2023-02-05 15:59:12
...,...,...,...,...,...,...,...,...,...,...
5845,100001475274247,Michelle Bianchi,865107857005917,1646980522151976,2021-04-27 07:22:23,NaN,4,37,92,2023-02-05 15:59:12
5846,100041894790295,Nella Horna,865107857005917,1646765442173484,2021-04-26 23:39:51,I absolutely adored this book!! Couldnâ€™t stop ...,9,0,11,2023-02-05 15:59:12
5847,598250441,Pooja Jagtiaani,865107857005917,1648622268654468,2021-04-29 19:38:34,#bookreview Five Years From Now by Paige Toon,0,0,1,2023-02-05 15:59:12
5848,1446679893,Lisa Christensen,865107857005917,1634108816772480,2021-04-08 08:04:19,This book tugged at my heart! I knew nothing o...,15,0,29,2023-02-05 15:59:12
5849,1446679893,Lisa Christensen,865107857005917,1645005852349443,2021-04-24 05:59:50,I received a package from the Library today!,2,2,58,2023-02-05 15:59:12

In [3]:
# imp config and cookie files generated from cURL commands made during the request

import requests

cookies = {
    'datr': 'aH65YyzZJ288kDWq1Kz_vsFA',
    'sb': 'en_BY9r-UFe27Lift9mRq8TN',
    'dpr': '1.25',
    'wd': '1536x718',
    'locale': 'en_GB',
    'c_user': '100090125020023',
    'xs': '26%3A_5iOKjcsQ88ijw%3A2%3A1675704689%3A-1%3A-1',
    'fr': '0hAIVZZUhersgBUtU.AWU37gWki4w0sanHQ9lP1iHAHbI.BjwX96.Oj.AAA.0.0.Bj4Tlr.AWVN5Wsw4r0',
    'm_page_voice': '100090125020023',
}

headers = {
    'authority': 'mbasic.facebook.com',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
    'accept-language': 'en-US,en;q=0.6',
    'cache-control': 'max-age=0',
    # 'cookie': 'datr=aH65YyzZJ288kDWq1Kz_vsFA; sb=en_BY9r-UFe27Lift9mRq8TN; dpr=1.25; wd=1536x718; locale=en_GB; c_user=100090125020023; xs=26%3A_5iOKjcsQ88ijw%3A2%3A1675704689%3A-1%3A-1; fr=0hAIVZZUhersgBUtU.AWU37gWki4w0sanHQ9lP1iHAHbI.BjwX96.Oj.AAA.0.0.Bj4Tlr.AWVN5Wsw4r0; m_page_voice=100090125020023',
    'referer': 'https://mbasic.facebook.com/search/top/?q=mark+zuck&refid=7&_rdr',
    'sec-ch-ua': '"Not_A Brand";v="99", "Brave";v="109", "Chromium";v="109"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': '"Android"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-user': '?1',
    'sec-gpc': '1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36',
}

params = {
    'eav': 'AfZHWt5drWaCODppjq1YgJs8n_D7ODuqmDTPAU4gLlYL5Yso1x5N41JY11klEU88Aqs',
    'refid': '46',
    '__xts__[0]': '12.AboP0hYH_MHnsUOj3mBXuDAO7zMGrZIagK0NW3eooqFeQnSOPs1K4DeWp42q6oPtXFgkvK2qGJ3FzfZydFmGNQeSTTzWf6aYCI1FLgZwXp0ZRq2rl9pg7fHbzorMy40ouYtj1u4xlcW59mjf7kNNrYqyEqdCTBiMjnjuG9xAKUuMg6FynydtDQ4qMy4aIwE2Cnqw9ZzL5ebXAJXPn_ihMKOAaaHfMpmXsoFO9PhR8xaVo2O38E5qxwrm0voYLVAtVif__kV9dl8gXYeKo_fnT0JbL7WhyMVdC6FqygRJ2oI6TVA28OGT1I07cfMAZa-0--5rP2ux6n-A_7-YdR3W2450Q97vG7rSpmY23vQDkS8ksnvLeJb00hlTao9q4Uw3B4_GJZ4kS9o3pERZ1rejZ_5TAr4xJEA74Vg8iTzh5RtGqHPNTMzQwbtWq13fqHIs5Hi-nK7KkQvWn-wIafwotQ0ZAbLs8TijCs4Hpp0RAJ_cUofvFlC22KxzgqZzd3DrDkB96NTfLzmfkP5btIDmJON6',
    'paipv': '0',
}

# response = requests.get('https://mbasic.facebook.com/zuck', params=params, cookies=cookies, headers=headers)

In [34]:
df2 = pd.read_csv("flagged/FB_ScrapedFinal2.csv")
df2["Gender"].value_counts()

Female    244
Null      236
Male       24
Name: Gender, dtype: int64

In [34]:
import bs4

genders = []
locs = []

def get_gender(binfo_html):
    if binfo_html is None : return "Null"

    soup = bs4.BeautifulSoup(str(binfo_html), "lxml")
    for div in soup.find_all("div"):
        try: 
            content = str(div.contents[0])
        except Exception:
            continue

        if content == "Male":
            return "Male"
        elif content == "Female":
            return "Female"
        
    return "Null"

def get_location(locinfo_html):
    if locinfo_html is None : return "Null"

    soup = bs4.BeautifulSoup(str(locinfo_html), "lxml")
    loc_table = soup.find_all("table")
    if loc_table is None:
        return "Null"

    if len(loc_table) <= 1:
        return "Null"

    return loc_table[1].text

for ind, user in enumerate(df["ACTORID"]):
    if ind <= 3900 : continue
    user_link = f"https://mbasic.facebook.com/{''.join(str(user).split(' '))}"
    try:
        response = requests.get(user_link, params=params, cookies=cookies, headers=headers)
    except Exception:
        # In case FB temporarily suspends the account, this exception cause will be triggered and script wont break
        genders.extend(["Null" for _ in range(len(list(df["ACTORID"])) - (ind+1))])

    soup = bs4.BeautifulSoup(response.text, "lxml")
    basic_info = soup.find("div", id = "basic-info")
    loc_info = soup.find("div", id = "living")
    
    user_gender = get_gender(basic_info)
    genders.append(user_gender)

    user_loc = get_location(loc_info)
    locs.append(user_loc)
    if ind == 4300 : break
    
genders, locs

(['Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Null',
  'Null',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Male',
  'Null',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Null',
  'Null',
  'Null',
  'Male',
  'Null',
  'Null',
  'Null',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Male',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Null',
  'Null',
  'Null',
  'Null',
  'Female',
  'Female',
  'Null',
  'Null',
  'Male',
  'Null',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Female',
  'Null',
  'Female',
  'Male',
  'Female',
  'Female',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Female',
  'Null',
  'Null',
  'Null',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Male',
  'Female',
  'Female',
  'Female',
  'Female',
  'Male',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Male',
  'Female',
  'Female',
  'Male',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Null',
  'Null',
  'Null',
  'Female',
  'Female',
  'Female',
  'Male',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Male',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Male',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Null',
  'Female',
  'Male',
  'Null',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Male',
  'Null',
  'Female',
  'Female',
  'Null',
  'Female',
  'Male',
  'Female',
  'Female',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Male',
  'Female',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Female',
  'Male',
  'Female',
  'Null',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Null',
  'Male',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Male',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Female',
  'Male',
  'Female',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Null',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Male',
  'Null',
  'Female',
  'Female',
  'Female',
  'Female',
  'Null',
  'Female',
  'Female',
  'Null',
  'Null',
  'Female',
  'Female',
  'Female',
  'Null',
  'Male',
  'Null',
  'Null',
  'Null',
  'Null',
  'Null'],
 ['Current town/cityHammond, Louisiana',
  'Null',
  'Null',
  'Null',
  'Current town/cityChesterfield',
  'Null',
  'Current town/cityFort Worth, Texas',
  'Current town/cityTampa, Florida',
  'Null',
  'Home townChilliwack, British Columbia',
  'Null',
  'Current town/cityScranton, Pennsylvania',
  'Null',
  'Null',
  'Current town/cityStudio City',
  'Null',
  'Null',
  'Home townMiami, Florida',
  'Null',
  'Null',
  'Null',
  'Current town/cityDetroit, Michigan',
  'Null',
  'Current town/cityBuffalo, Minnesota',
  'Current town/cityChicago, Illinois',
  'Null',
  'Null',
  'Current town/cityMadrid, Spain',
  'Null',
  'Current town/cityMoneta, Virginia',
  'Current town/cityDallas, Texas',
  'Null',
  'Null',
  'Null',
  'Current town/cityFall Branch, Tennessee',
  'Null',
  'Null',
  'Current town/cityBloomington, Minnesota',
  'Null',
  'Null',
  'Current town/cityLone Tree, Colorado',
  'Current town/cityMadrid, Spain',
  'Null',
  'Null',
  'Current town/cityMarlborough, Connecticut',
  'Null',
  'Current town/cityChicago, Illinois',
  'Moved in 2020Euless, Texas',
  'Current town/cityBlack Mountain, North Carolina',
  'Home townNew York, New York',
  'Null',
  'Current town/cityAshton-under-Lyne',
  'Current town/cityMurrells Inlet, South Carolina',
  'Current town/cityCarrollton, Missouri',
  'Home townBay City, Michigan',
  'Current town/cityMcLeansville, North Carolina',
  'Home townBirmingham, United Kingdom',
  'Null',
  'Null',
  'Null',
  'Current town/cityPhiladelphia, Pennsylvania',
  'Current town/cityPlano, Texas',
  'Null',
  'Null',
  'Current town/cityThe Woodlands, Texas',
  'Current town/cityOlympia, Washington',
  'Null',
  'Null',
  'Current town/cityMonterrey, Nuevo Leon, Mexico',
  'Null',
  'Null',
  'Null',
  'Null',
  'Null',
  'Current town/cityMadrid, Spain',
  'Null',
  'Current town/cityBuffalo, Minnesota',
  'Null',
  'Current town/cityMorganville',
  'Null',
  'Current town/cityRaleigh, North Carolina',
  'Null',
  'Null',
  'Current town/cityKarachi, Pakistan',
  'Current town/cityMonroeville, Pennsylvania',
  'Current town/cityAtlanta, Georgia',
  'Current town/cityVaasa, Finland',
  'Current town/cityCairo, Egypt',
  'Null',
  'Current town/cityOlympia, Washington',
  'Null',
  'Current town/cityTampa, Florida',
  'Null',
  'Current town/cityNew Freedom, Pennsylvania',
  'Home townNew York, New York',
  'Current town/cityToronto, Ontario',
  'Null',
  'Null',
  'Null',
  'Current town/cityCairo, Egypt',
  'Null',
  'Moved in 2014Anlaby Common',
  'Current town/cityMadrid, Spain',
  'Null',
  'Null',
  'Current town/cityMonroeville, Pennsylvania',
  'Current town/citySkelmersdale',
  'Current town/cityMadrid, Spain',
  'Null',
  'Null',
  'Null',
  'Current town/cityMadrid, Spain',
  'Current town/cityNottingham, United Kingdom',
  'Null',
  'Moved in 2004Stoneham, Massachusetts',
  'Null',
  'Current town/cityGreer, South Carolina',
  'Home townToronto, Ontario',
  'Current town/cityWickenburg, Arizona',
  'Current town/cityOlympia, Washington',
  'Current town/cityTampa, Florida',
  'Home townLowestoft',
  'Current town/cityCarrollton, Missouri',
  'Null',
  'Null',
  'Null',
  'Current town/cityUlaanbaatar, Mongolia',
  'Null',
  'Null',
  'Current town/cityNottingham, United Kingdom',
  'Null',
  'Null',
  'Null',
  'Null',
  'Null',
  'Home townSchenectady, New York',
  'Current town/cityOlympia, Washington',
  'Current town/cityOlympia, Washington',
  'Current town/cityPeru, Nebraska',
  'Null',
  'Home townChilliwack, British Columbia',
  'Null',
  'Current town/cityChesterfield',
  'Current town/cityWashington D.C.',
  'Current town/cityBloomington, Minnesota',
  'Null',
  'Current town/cityParkland, Florida',
  'Current town/cityWest Gilgo Beach, New York',
  'Current town/cityBoston, Massachusetts',
  'Current town/cityChicago, Illinois',
  'Current town/cityAtlanta, Georgia',
  'Moved in 1994Cabo San Lucas, Baja California Sur',
  'Null',
  'Current town/cityModesto, California',
  'Null',
  'Home townShrewsbury, Shropshire',
  'Null',
  'Current town/cityNottingham, United Kingdom',
  'Current town/cityGlendale, Ohio',
  'Current town/cityPhiladelphia, Pennsylvania',
  'Current town/cityNottingham, United Kingdom',
  'Current town/cityScranton, Pennsylvania',
  'Current town/cityAshburn, Virginia',
  'Current town/cityChicago, Illinois',
  'Current town/cityDurham, New Hampshire',
  'Current town/cityTampa, Florida',
  'Current town/cityChicago, Illinois',
  'Null',
  'Current town/cityMesa, Arizona',
  'Null',
  'Null',
  'Current town/cityWashington D.C.',
  'Null',
  'Current town/cityMadrid, Spain',
  'Null',
  'Current town/cityKernersville, North Carolina',
  'Null',
  'Current town/cityTomah, Wisconsin',
  'Null',
  'Current town/cityVassar, Michigan',
  'Null',
  'Current town/cityTampa, Florida',
  'Current town/cityClayton, Georgia',
  'Null',
  'Current town/cityTampa, Florida',
  'Current town/cityRajshahi',
  'Current town/cityTampa, Florida',
  'Current town/cityGreer, South Carolina',
  'Null',
  'Null',
  'Current town/cityArnold, Maryland',
  'Current town/cityWickenburg, Arizona',
  'Current town/cityScranton, Pennsylvania',
  'Current town/cityHamilton, New Zealand',
  'Current town/cityBloomington, Minnesota',
  'Null',
  'Current town/cityMonroeville, Pennsylvania',
  'Current town/cityToms River, New Jersey',
  'Current town/cityToms River, New Jersey',
  'Null',
  'Current town/cityThousand Oaks, California',
  'Null',
  'Null',
  'Current town/cityOrange Beach, Alabama',
  'Null',
  'Home townChilliwack, British Columbia',
  'Current town/cityHummelstown, Pennsylvania',
  'Null',
  'Current town/cityTel Aviv, Israel',
  'Null',
  'Current town/cityMesquite, Nevada',
  'Current town/cityToronto, Ontario',
  'Current town/cityRichmond, Virginia',
  'Null',
  'Null',
  'Null',
  'Current town/cityLake Worth, Florida',
  'Null',
  'Null',
  'Null',
  'Current town/cityAtlanta, Georgia',
  'Null',
  'Null',
  'Current town/cityWickenburg, Arizona',
  'Current town/cityOgden, Utah',
  'Current town/cityMadrid, Spain',
  'Current town/cityToronto, Ontario',
  'Current town/cityMinneapolis, Minnesota',
  'Null',
  'Null',
  'Current town/cityChesterfield',
  'Null',
  'Moved in 2016Rossville, Kansas',
  'Null',
  'Null',
  'Current town/cityChatham, Illinois',
  'Home townLondon, United Kingdom',
  'Null',
  'Null',
  'Current town/cityChesterfield',
  'Current town/citySeattle, Washington',
  'Current town/cityAlhaurÃ­n El Grande, Andalucia, Spain',
  'Null',
  'Current town/cityKernersville, North Carolina',
  'Current town/cityGlovertown, Newfoundland and Labrador',
  'Null',
  'Null',
  'Current town/cityGreenacres, Florida',
  'Null',
  'Null',
  'Current town/cityToms River, New Jersey',
  'Current town/cityPleasanton, California',
  'Current town/cityScranton, Pennsylvania',
  'Null',
  'Current town/cityPalm Coast, Florida',
  'Current town/cityMadrid, Spain',
  'Current town/cityMinneapolis, Minnesota',
  'Current town/cityChicago, Illinois',
  'Null',
  'Current town/cityChesterfield',
  'Current town/cityChesapeake, Virginia',
  'Current town/citySmyrna, Tennessee',
  'Null',
  'Current town/cityChicago, Illinois',
  'Null',
  'Null',
  'Current town/cityMadrid, Spain',
  'Null',
  'Null',
  'Null',
  'Moved hereWonder Lake, Illinois',
  'Current town/cityMadrid, Spain',
  'Null',
  'Current town/cityOzark, Missouri',
  'Current town/cityRinggold, Virginia',
  'Current town/citySeven Lakes, North Carolina',
  'Current town/cityWinnipeg, Manitoba',
  'Null',
  'Current town/cityKingston, New York',
  'Current town/cityAdelaide, South Australia',
  'Null',
  'Home townDublin, Ireland',
  'Current town/cityJohannesburg, Gauteng',
  'Current town/cityTampa, Florida',
  'Null',
  'Current town/cityBargaintown',
  'Current town/cityMadrid, Spain',
  'Null',
  'Null',
  'Null',
  'Current town/cityCamp Hill, Pennsylvania',
  'Null',
  'Current town/cityMishawaka, Indiana',
  'Current town/cityColumbus, Ohio',
  'Current town/cityAtlanta, Georgia',
  'Null',
  'Moved in 2016Rossville, Kansas',
  'Null',
  'Moved in 2014Anlaby Common',
  'Current town/cityBuffalo, Minnesota',
  'Null',
  'Null',
  'Current town/cityLevel Green, Pennsylvania',
  'Null',
  'Current town/cityTampa, Florida',
  'Current town/cityWickenburg, Arizona',
  'Null',
  'Null',
  'Current town/cityCarrollton, Missouri',
  'Null',
  'Null',
  'Null',
  'Null',
  'Null',
  'Null',
  'Null',
  'Null',
  'Current town/cityChicago, Illinois',
  'Current town/cityTampa, Florida',
  'Null',
  'Null',
  'Null',
  'Null',
  'Current town/cityTampa, Florida',
  'Current town/cityBuffalo, Minnesota',
  'Null',
  'Null',
  'Null',
  'Current town/cityWest Coast',
  'Null',
  'Null',
  'Current town/cityMadrid, Spain',
  'Current town/cityAtlanta, Georgia',
  'Null',
  'Null',
  'Moved in 2014Anlaby Common',
  'Null',
  'Current town/cityChicago, Illinois',
  'Null',
  'Current town/cityBeamsville, Ontario',
  'Current town/cityKernersville, North Carolina',
  'Current town/cityScranton, Pennsylvania',
  'Current town/cityCulpeper, Virginia',
  'Current town/cityChicago, Illinois',
  'Current town/cityParamus, New Jersey',
  'Current town/cityPortland, Tennessee',
  'Current town/cityPhiladelphia, Pennsylvania',
  'Null',
  'Home townGapan, Nueva Ecija',
  'Null',
  'Current town/cityChicago, Illinois',
  'Home townChilliwack, British Columbia',
  'Null',
  'Null',
  'Null',
  'Null',
  'Null',
  'Current town/cityClayton, Georgia',
  'Current town/citySydney, Australia',
  'Current town/cityToronto, Ontario',
  'Null',
  'Null',
  'Null',
  'Current town/cityMonroeville, Pennsylvania',
  'Null',
  'Null',
  'Moved in 2004Stoneham, Massachusetts',
  'Null',
  'Current town/cityCarrollton, Missouri',
  'Current town/cityWinnipeg, Manitoba',
  'Current town/citySydney, Australia',
  'Null',
  'Current town/cityBaton Rouge, Louisiana',
  'Null',
  'Moved in 2016Rossville, Kansas',
  'Current town/cityMesquite, Nevada',
  'Moved in 2004Stoneham, Massachusetts',
  'Null',
  'Null',
  'Current town/cityBloomington, Minnesota',
  'Current town/cityLevin, New Zealand',
  'Null',
  'Current town/cityAtlanta, Georgia',
  'Home townChilliwack, British Columbia',
  'Null',
  'Null',
  'Current town/cityMadrid, Spain',
  'Current town/citySydney, Australia',
  'Null',
  'Null',
  'Current town/cityTampa, Florida',
  'Current town/cityScranton, Pennsylvania',
  'Current town/cityWickenburg, Arizona',
  'Null',
  'Current town/cityColumbus, Ohio',
  'Current town/cityPalm Coast, Florida',
  'Home townFair Lawn, New Jersey',
  'Null',
  'Current town/cityKansas City, Kansas',
  'Current town/cityToronto, Ontario'])

In [36]:
import pickle

file_count = 1
with open(f"flagged/genders_pt{file_count}.pkl", "wb") as f:
    pickle.dump(genders, f)
with open(f"flagged/locations_pt{file_count}.pkl", "wb") as f:
    pickle.dump(locs, f)

In [5]:
# 0-300
# 301-650
# 651-1000
# 1001-1400
# 1401-1800
# 1801-2200
# 2201-2559
# 2560-2800
# 2801-3200
# 3201-3500
# 3501-3900

# 2560

print(df["ACTORID"].iloc[2560])

# locs[:-41]


# 2600-41

100007948114035

In [33]:
# len(genders)
import pickle

sum = 0
for i in range(1, 10):
    with open(f"flagged/genders_pt{i}.pkl", "rb") as f:
        loaded_locs = pickle.load(f)
        print(len(loaded_locs))
        sum += len(loaded_locs)

with open(f"flagged/genders_ptbw_7_8.pkl", "rb") as f:
    loaded_locs = pickle.load(f)
    sum += len(loaded_locs)

sum

301
350
350
400
400
400
359
400
300

3501

In [30]:
genders_final = []
for i in range(1, 8):
    with open(f"flagged/genders_pt{i}.pkl", "rb") as f:
        genders_final.extend(pickle.load(f))

genders_final.extend(pickle.loads())

with open(f"flagged/genders_ptbw_7_8.pkl", "rb") as f:
    loaded_locs = pickle.load(f)
    sum += len(loaded_locs)

3500